### ISSUE TITLE
Create-hls and make-vivado-proj?

### ISSUE THREAD

**Issue by ghost** [onioncc/iSmartDNN#1]
Hi,

  It's a great repository.  I'm trying to rebuild your project for hardware. But I didn't know the `config_clkperiod` and `PYNQ-Z1_C.xdx`.
  I'm wonder if you can provide the `create_hls.tcl` and `make-vivado-proj.tcl` as reference?
  Thanks!

**Comment by jinsanko** [comment]
I can generate IP with Vivado_HLS 2018.2 GUI, can not do it with 2017.3.
